name: weather_unit
description: Providing weather unit in Dart
homepage: https://www.rk0cc.xyz
repository: https://github.com/Weanel/weather_unit
version: 1.0.0
environment: 
  sdk: ">=2.10.0 <3.0.0"
dev_dependencies:
  test: ^1.17.10